# fitz_sage/engines/fitz_krag/retrieval/router.py
"""
Retrieval router — dispatches queries to BM25/keyword strategies and merges
results. fitz-sage has no dense embeddings: there is no generated hypothetical
document leg, no chunk fallback, no per-query embedding pre-computation. The
router reads gates and query expansions from the RetrievalProfile.
"""

from __future__ import annotations

import logging
import time as _time
from concurrent.futures import Future, ThreadPoolExecutor
from typing import TYPE_CHECKING, Any

from fitz_sage.engines.fitz_krag.evidence_compiler import (
    query_has_code_obligation,
    query_has_table_obligation,
)
from fitz_sage.engines.fitz_krag.retrieval.query_coverage import (
    compound_queries,
    ensure_query_coverage,
    merge_retrieval_provenance,
    tag_retrieval_query,
)
from fitz_sage.engines.fitz_krag.retrieval.trace import addresses_trace
from fitz_sage.engines.fitz_krag.types import Address, AddressKind

if TYPE_CHECKING:
    from fitz_sage.engines.fitz_krag.config.schema import FitzKragConfig
    from fitz_sage.engines.fitz_krag.retrieval.strategies.code_search import (
        CodeSearchStrategy,
    )
    from fitz_sage.engines.fitz_krag.retrieval.strategies.llm_code_search import (
        LlmCodeSearchStrategy,
    )
    from fitz_sage.engines.fitz_krag.retrieval.strategies.section_search import (
        SectionSearchStrategy,
    )
    from fitz_sage.engines.fitz_krag.retrieval.strategies.table_search import (
        TableSearchStrategy,
    )

logger = logging.getLogger(__name__)


class RetrievalRouter:
    """Routes queries to available strategies, merges results."""

    def __init__(
        self,
        code_strategy: "CodeSearchStrategy | LlmCodeSearchStrategy",
        config: "FitzKragConfig",
        section_strategy: "SectionSearchStrategy | None" = None,
        table_strategy: "TableSearchStrategy | None" = None,
    ):
        self._code_strategy = code_strategy
        self._section_strategy = section_strategy
        self._table_strategy = table_strategy
        self._config = config
        self.last_trace: dict[str, Any] = {}

    def retrieve(
        self,
        query: str,
        profile: Any = None,
        rewrite_result: "Any | None" = None,
    ) -> list[Address]:
        """
        Retrieve addresses using strategy weights from retrieval profile.

        When profile is provided, strategies with near-zero weight are skipped
        and results are ranked using CrossStrategyRanker. Without a profile,
        all configured strategies run with equal weight.
        """
        from fitz_sage.engines.fitz_krag.retrieval.ranker import CrossStrategyRanker

        limit = profile.top_k if profile else self._config.top_addresses
        weights = profile.strategy_weights if profile else None
        all_addresses: list[Address] = []
        strategy_calls: list[dict[str, Any]] = []

        # Collect queries to run (original + profile expansions + multi-query)
        # Each entry is (query_text, tag) where tag is used for temporal metadata
        tagged_queries: list[tuple[str, str | None]] = [(query, None)]
        if profile:
            if profile.query_variations:
                # Tag temporal variations with their reference text
                temporal_refs = profile.temporal_references
                for i, variation in enumerate(profile.query_variations):
                    tag = temporal_refs[i] if i < len(temporal_refs) else None
                    tagged_queries.append((variation, tag))
            if profile.comparison_queries:
                # Use comparison queries already generated by ComparisonModule
                for cq in profile.comparison_queries:
                    tagged_queries.append((cq, None))
            elif profile.comparison_entities:
                # Fallback: naive entity expansion (no LLM call)
                for entity in profile.comparison_entities:
                    tagged_queries.append((f"{query} {entity}", None))

            # Semantic keyword leg — synonyms/acronyms/related terms from
            # the query-prep bus, run as one extra BM25 query for recall.
            if profile.keywords:
                tagged_queries.append((" ".join(profile.keywords), None))

        # Rewrites, decomposed clauses, and ambiguity branches are all recall legs.
        rewrite_variations = rewrite_result.all_query_variations if rewrite_result else []
        for variation in rewrite_variations:
            tagged_queries.append((variation, None))

        tagged_queries = list(dict.fromkeys(tagged_queries))
        unique_queries = list(dict.fromkeys(q for q, _ in tagged_queries))
        logger.debug(
            f"Retrieval gates: type={profile.analysis_type if profile else 'none'}, "
            f"conf={profile.analysis_confidence if profile else 0:.2f}, "
            f"queries={len(unique_queries)}"
        )

        # Submit all strategy calls concurrently
        _t_strategies = _time.perf_counter()
        pool = ThreadPoolExecutor(max_workers=self._config.retrieval_workers)
        futures: list[tuple[Future, str | None, str, str]] = []
        try:
            for q, temporal_tag in tagged_queries:
                if (
                    not weights
                    or weights.get("code", 1.0) > 0.05
                    or query_has_code_obligation(q, profile)
                ):
                    fut = pool.submit(self._run_strategy, self._code_strategy, q, limit, profile)
                    futures.append((fut, temporal_tag, type(self._code_strategy).__name__, q))

                if self._section_strategy and (not weights or weights.get("section", 1.0) > 0.05):
                    fut = pool.submit(self._run_strategy, self._section_strategy, q, limit, profile)
                    futures.append((fut, temporal_tag, type(self._section_strategy).__name__, q))

                if self._table_strategy and (
                    not weights
                    or weights.get("table", 1.0) > 0.05
                    or query_has_table_obligation(q, profile)
                ):
                    fut = pool.submit(self._run_strategy, self._table_strategy, q, limit, profile)
                    futures.append((fut, temporal_tag, type(self._table_strategy).__name__, q))

            # Collect strategy results
            for fut, temporal_tag, strategy_name, strategy_query in futures:
                try:
                    batch = fut.result(timeout=600)
                    batch = tag_retrieval_query(batch, strategy_query)
                    strategy_call = {
                        "strategy": strategy_name,
                        "query": strategy_query,
                        "temporal_tag": temporal_tag,
                        "count": len(batch),
                        "addresses": addresses_trace(batch),
                    }
                    if temporal_tag:
                        batch = self._tag_temporal(batch, temporal_tag)
                        strategy_call["tagged_addresses"] = addresses_trace(batch)
                    all_addresses.extend(batch)
                    strategy_calls.append(strategy_call)
                except Exception as e:
                    strategy_calls.append(
                        {
                            "strategy": strategy_name,
                            "query": strategy_query,
                            "temporal_tag": temporal_tag,
                            "count": 0,
                            "error": str(e),
                            "addresses": [],
                        }
                    )
                    logger.warning(f"Strategy failed: {e}")

        finally:
            pool.shutdown(wait=False, cancel_futures=True)

        _strategies_ms = (_time.perf_counter() - _t_strategies) * 1000
        logger.debug(f"Retrieval breakdown: strategies={_strategies_ms:.0f}ms")

        # Corpus summary injection for broad/thematic queries
        inject_summaries = profile.inject_corpus_summaries if profile else False
        corpus_summary_trace: dict[str, Any] = {
            "enabled": bool(self._section_strategy and inject_summaries),
            "count": 0,
            "addresses": [],
        }
        if self._section_strategy and inject_summaries:
            try:
                corpus_addresses = self._section_strategy.retrieve(
                    query, limit=limit, detection=profile, inject_corpus_summaries=True
                )
                corpus_addresses = tag_retrieval_query(corpus_addresses, query)
                all_addresses.extend(corpus_addresses)
                corpus_summary_trace["count"] = len(corpus_addresses)
                corpus_summary_trace["addresses"] = addresses_trace(corpus_addresses)
                logger.debug(f"Injected {len(corpus_addresses)} corpus summary chunk(s)")
            except Exception as e:
                corpus_summary_trace["error"] = str(e)
                logger.debug(f"Corpus summary injection skipped: {e}")

        # Deduplicate
        raw_addresses = list(all_addresses)
        deduped = self._deduplicate(all_addresses)

        # Rank using profile if available
        if profile:
            ranker = CrossStrategyRanker()
            ranked = ranker.rank(deduped, profile)
        else:
            # Fallback: sort by score
            deduped.sort(key=lambda a: a.score, reverse=True)
            ranked = deduped

        # File diversity: prevent one file from monopolizing all read slots
        ranked = self._enforce_file_diversity(ranked)
        final = self._enforce_strategy_coverage(ranked, limit)
        required_queries = compound_queries(rewrite_result)
        final = ensure_query_coverage(
            ranked,
            final,
            required_queries,
            limit=limit,
        )
        self.last_trace = {
            "query": query,
            "limit": limit,
            "strategy_weights": dict(weights or {}),
            "tagged_queries": [
                {"query": query_text, "temporal_tag": temporal_tag}
                for query_text, temporal_tag in tagged_queries
            ],
            "unique_query_count": len(unique_queries),
            "compound_queries": required_queries,
            "strategy_calls": strategy_calls,
            "corpus_summary": corpus_summary_trace,
            "raw_candidate_count": len(raw_addresses),
            "raw_candidates": addresses_trace(raw_addresses),
            "deduped_count": len(deduped),
            "deduped": addresses_trace(deduped),
            "ranked_count": len(ranked),
            "ranked": addresses_trace(ranked),
            "final_count": len(final),
            "final": addresses_trace(final),
            "timings_ms": {"strategies": _strategies_ms},
        }
        return final

    def _run_strategy(
        self,
        strategy: Any,
        query: str,
        limit: int,
        profile: Any,
    ) -> list[Address]:
        """Run a single strategy."""
        try:
            results = strategy.retrieve(query, limit, detection=profile)
            return [result for result in results if isinstance(result, Address)]
        except Exception as e:
            logger.warning(f"{type(strategy).__name__} failed for '{query[:50]}': {e}")
            return []

    def _tag_temporal(self, addresses: list[Address], ref_text: str) -> list[Address]:
        """Tag addresses with the temporal reference that produced them."""
        tagged: list[Address] = []
        for addr in addresses:
            meta = dict(addr.metadata)
            existing = meta.get("temporal_refs", [])
            if ref_text not in existing:
                meta["temporal_refs"] = existing + [ref_text]
            tagged.append(
                Address(
                    kind=addr.kind,
                    source_id=addr.source_id,
                    location=addr.location,
                    summary=addr.summary,
                    score=addr.score,
                    metadata=meta,
                )
            )
        return tagged

    def _deduplicate(self, addresses: list[Address]) -> list[Address]:
        """Deduplicate addresses while retaining query-leg provenance."""
        seen: dict[tuple[str, str], int] = {}
        result: list[Address] = []

        for addr in addresses:
            key = (addr.source_id, addr.location)
            if key not in seen:
                seen[key] = len(result)
                result.append(addr)
            else:
                idx = seen[key]
                result[idx] = merge_retrieval_provenance(result[idx], addr)

        return result

    @staticmethod
    def _enforce_file_diversity(addresses: list[Address], max_per_file: int = 3) -> list[Address]:
        """Reorder addresses so no single file monopolizes the top slots.

        Preserves ranking order but defers excess addresses from any one file
        to the end of the list. With max_per_file=3 and top_addresses=5,
        at least 2 different files appear in the top results.
        """
        file_counts: dict[str, int] = {}
        promoted: list[Address] = []
        deferred: list[Address] = []

        for addr in addresses:
            count = file_counts.get(addr.source_id, 0)
            if count < max_per_file:
                promoted.append(addr)
                file_counts[addr.source_id] = count + 1
            else:
                deferred.append(addr)

        return promoted + deferred

    @staticmethod
    def _enforce_strategy_coverage(
        addresses: list[Address],
        limit: int,
        minimum_per_strategy: int = 2,
    ) -> list[Address]:
        """Keep a small recall foothold for each strategy that found candidates."""
        selected = list(addresses[:limit])
        if len(selected) >= len(addresses) or minimum_per_strategy <= 0:
            return selected

        def strategy(address: Address) -> str:
            if address.kind in {AddressKind.SYMBOL, AddressKind.FILE}:
                return "code"
            return address.kind.value

        available: dict[str, int] = {}
        for address in addresses:
            name = strategy(address)
            available[name] = available.get(name, 0) + 1
        targets = {name: min(minimum_per_strategy, count) for name, count in available.items()}
        selected_counts: dict[str, int] = {}
        for address in selected:
            name = strategy(address)
            selected_counts[name] = selected_counts.get(name, 0) + 1

        for missing_strategy, target in targets.items():
            while selected_counts.get(missing_strategy, 0) < target:
                replacement = next(
                    (
                        address
                        for address in addresses[limit:]
                        if strategy(address) == missing_strategy and address not in selected
                    ),
                    None,
                )
                if replacement is None:
                    break
                replace_at = next(
                    (
                        index
                        for index in range(len(selected) - 1, -1, -1)
                        if selected_counts[strategy(selected[index])]
                        > targets[strategy(selected[index])]
                    ),
                    None,
                )
                if replace_at is None:
                    break
                removed_strategy = strategy(selected[replace_at])
                selected[replace_at] = replacement
                selected_counts[removed_strategy] -= 1
                selected_counts[missing_strategy] = selected_counts.get(missing_strategy, 0) + 1
        return selected
