# fitz_sage/engines/fitz_krag/retrieval/router.py
"""
Retrieval router — dispatches queries to BM25/keyword strategies and merges
results. fitz-sage has no dense embeddings: there is no HyDE leg, no chunk
fallback, no per-query embedding pre-computation. The router reads gates
and query expansions from the RetrievalProfile.
"""

from __future__ import annotations

import logging
import time as _time
from concurrent.futures import Future, ThreadPoolExecutor
from typing import TYPE_CHECKING, Any, Callable

from fitz_sage.core.json_utils import parse_llm_json
from fitz_sage.engines.fitz_krag.types import Address

if TYPE_CHECKING:
    from fitz_sage.engines.fitz_krag.config.schema import FitzKragConfig
    from fitz_sage.engines.fitz_krag.retrieval.strategies.code_search import (
        CodeSearchStrategy,
    )
    from fitz_sage.engines.fitz_krag.retrieval.strategies.llm_code_search import (
        LlmCodeSearchStrategy,
    )
    from fitz_sage.engines.fitz_krag.retrieval.strategies.section_search import (
        SectionSearchStrategy,
    )
    from fitz_sage.engines.fitz_krag.retrieval.strategies.table_search import (
        TableSearchStrategy,
    )

logger = logging.getLogger(__name__)


class RetrievalRouter:
    """Routes queries to available strategies, merges results."""

    def __init__(
        self,
        code_strategy: "CodeSearchStrategy | LlmCodeSearchStrategy",
        config: "FitzKragConfig",
        section_strategy: "SectionSearchStrategy | None" = None,
        table_strategy: "TableSearchStrategy | None" = None,
        chat_factory: Any = None,
        agentic_strategy: Any = None,
    ):
        self._code_strategy = code_strategy
        self._section_strategy = section_strategy
        self._table_strategy = table_strategy
        self._config = config
        self._chat_factory = chat_factory
        self._agentic_strategy = agentic_strategy
        self._keyword_matcher: Any = None  # Set by engine for vocabulary filtering

    def retrieve(
        self,
        query: str,
        profile: Any = None,
        rewrite_result: "Any | None" = None,
        progress: Callable[[str], None] | None = None,
    ) -> list[Address]:
        """
        Retrieve addresses using strategy weights from retrieval profile.

        When profile is provided, strategies with near-zero weight are skipped
        and results are ranked using CrossStrategyRanker. Without profile,
        all strategies run equally (backward compatible).
        """
        from fitz_sage.engines.fitz_krag.retrieval.ranker import CrossStrategyRanker

        limit = profile.top_k if profile else self._config.top_addresses
        weights = profile.strategy_weights if profile else None
        all_addresses: list[Address] = []

        # Collect queries to run (original + profile expansions + multi-query)
        # Each entry is (query_text, tag) where tag is used for temporal metadata
        tagged_queries: list[tuple[str, str | None]] = [(query, None)]
        if profile:
            if profile.query_variations:
                # Tag temporal variations with their reference text
                temporal_refs = profile.temporal_references
                for i, variation in enumerate(profile.query_variations):
                    tag = temporal_refs[i] if i < len(temporal_refs) else None
                    tagged_queries.append((variation, tag))
            if profile.comparison_queries:
                # Use comparison queries already generated by ComparisonModule
                for cq in profile.comparison_queries:
                    tagged_queries.append((cq, None))
            elif profile.comparison_entities:
                # Fallback: naive entity expansion (no LLM call)
                for entity in profile.comparison_entities:
                    tagged_queries.append((f"{query} {entity}", None))

        # Multi-query expansion: prefer rewriter's decomposed queries over separate LLM call
        rewrite_variations = rewrite_result.all_query_variations if rewrite_result else []
        if len(rewrite_variations) > 1:
            # Rewriter already decomposed — use its variations (skip [0] = original)
            for var in rewrite_variations[1:]:
                tagged_queries.append((var, None))
        elif profile.run_multi_query if profile else False:
            # Fallback: only when rewriter is disabled or didn't decompose
            expanded = self._expand_query(query)
            for eq in expanded:
                tagged_queries.append((eq, None))

        run_agentic = profile.run_agentic if profile else True
        unique_queries = list(dict.fromkeys(q for q, _ in tagged_queries))
        logger.debug(
            f"Retrieval gates: agentic={run_agentic}, "
            f"type={profile.analysis_type if profile else 'none'}, "
            f"conf={profile.analysis_confidence if profile else 0:.2f}, "
            f"queries={len(unique_queries)}"
        )

        # Submit all strategy calls concurrently
        _t_strategies = _time.perf_counter()
        _progress = progress or (lambda _: None)
        pool = ThreadPoolExecutor(max_workers=self._config.retrieval_workers)
        futures: list[tuple[Future, str | None]] = []  # (future, temporal_tag)
        try:
            for q, temporal_tag in tagged_queries:
                if not weights or weights.get("code", 1.0) > 0.05:
                    fut = pool.submit(self._run_strategy, self._code_strategy, q, limit, profile)
                    futures.append((fut, temporal_tag))

                if self._section_strategy and (not weights or weights.get("section", 1.0) > 0.05):
                    fut = pool.submit(self._run_strategy, self._section_strategy, q, limit, profile)
                    futures.append((fut, temporal_tag))

                if self._table_strategy and (not weights or weights.get("table", 1.0) > 0.05):
                    fut = pool.submit(self._run_strategy, self._table_strategy, q, limit, profile)
                    futures.append((fut, temporal_tag))

            # Submit agentic search in the same pool
            agentic_future: Future | None = None
            if self._agentic_strategy and run_agentic:
                _progress("Agentic search: scanning unindexed files...")
                agentic_future = pool.submit(self._run_agentic, query, limit, _progress)

            # Collect strategy results
            for fut, temporal_tag in futures:
                try:
                    batch = fut.result(timeout=600)
                    if temporal_tag:
                        batch = self._tag_temporal(batch, temporal_tag)
                    all_addresses.extend(batch)
                except Exception as e:
                    logger.warning(f"Strategy failed: {e}")

            # Collect agentic results
            if agentic_future:
                try:
                    agentic_addresses = agentic_future.result(timeout=600)
                    all_addresses.extend(agentic_addresses)
                except Exception as e:
                    logger.warning(f"Agentic strategy failed: {e}")
        finally:
            pool.shutdown(wait=False, cancel_futures=True)

        _strategies_ms = (_time.perf_counter() - _t_strategies) * 1000
        logger.debug(f"Retrieval breakdown: strategies={_strategies_ms:.0f}ms")

        # Corpus summary injection for broad/thematic queries
        inject_summaries = profile.inject_corpus_summaries if profile else False
        if self._section_strategy and inject_summaries:
            try:
                corpus_addresses = self._section_strategy.retrieve(
                    query, limit=limit, detection=profile, inject_corpus_summaries=True
                )
                all_addresses.extend(corpus_addresses)
                logger.debug(f"Injected {len(corpus_addresses)} corpus summary chunk(s)")
            except Exception as e:
                logger.debug(f"Corpus summary injection skipped: {e}")

        # Deduplicate
        deduped = self._deduplicate(all_addresses)

        # Keyword vocabulary boost
        if self._keyword_matcher:
            deduped = self._apply_keyword_boost(query, deduped)

        # Rank using profile if available
        if profile:
            ranker = CrossStrategyRanker()
            ranked = ranker.rank(deduped, profile)
        else:
            # Fallback: sort by score
            deduped.sort(key=lambda a: a.score, reverse=True)
            ranked = deduped

        # File diversity: prevent one file from monopolizing all read slots
        ranked = self._enforce_file_diversity(ranked)
        return ranked[: self._config.top_addresses]

    def _run_strategy(
        self,
        strategy: Any,
        query: str,
        limit: int,
        profile: Any,
    ) -> list[Address]:
        """Run a single strategy."""
        try:
            return strategy.retrieve(query, limit, detection=profile)
        except Exception as e:
            logger.warning(f"{type(strategy).__name__} failed for '{query[:50]}': {e}")
            return []

    def _run_agentic(
        self,
        query: str,
        limit: int,
        progress: Callable[[str], None],
    ) -> list[Address]:
        """Run agentic search with progress reporting."""
        try:
            agentic_addresses = self._agentic_strategy.retrieve(query, limit)
            if agentic_addresses:
                paths = set()
                for a in agentic_addresses:
                    dp = a.metadata.get("disk_path")
                    if dp:
                        parts = dp.replace("\\", "/").split("/")
                        paths.add(parts[-1] if parts else dp)
                files_str = ", ".join(sorted(paths)[:5])
                progress(
                    f"Agentic search: found {len(agentic_addresses)} results "
                    f"from {len(paths)} files ({files_str})"
                )
            else:
                progress("Agentic search: no matching files found")
            return agentic_addresses
        except Exception as e:
            logger.warning(f"Agentic strategy failed: {e}")
            return []

    def _tag_temporal(self, addresses: list[Address], ref_text: str) -> list[Address]:
        """Tag addresses with the temporal reference that produced them."""
        tagged: list[Address] = []
        for addr in addresses:
            meta = dict(addr.metadata)
            existing = meta.get("temporal_refs", [])
            if ref_text not in existing:
                meta["temporal_refs"] = existing + [ref_text]
            tagged.append(
                Address(
                    kind=addr.kind,
                    source_id=addr.source_id,
                    location=addr.location,
                    summary=addr.summary,
                    score=addr.score,
                    metadata=meta,
                )
            )
        return tagged

    def _expand_query(self, query: str) -> list[str]:
        """Decompose a long query into focused sub-queries via LLM."""
        try:
            chat = self._chat_factory("fast")
            prompt = (
                "Break this complex query into 2-3 simpler, focused search queries.\n"
                "Return ONLY a JSON array of strings.\n\n"
                f"Query: {query}\n\n"
                'Output: ["query1", "query2", ...]'
            )
            response = chat.chat([{"role": "user", "content": prompt}])
            text = response.strip()
            parsed = parse_llm_json(text, as_array=True)
            return [str(q) for q in parsed[:3] if isinstance(q, str) and q.strip()]
        except Exception as e:
            logger.warning(f"Multi-query expansion failed: {e}")
        return []

    def _apply_keyword_boost(self, query: str, addresses: list[Address]) -> list[Address]:
        """Boost addresses matching vocabulary keywords found in the query."""
        try:
            matched_keywords = self._keyword_matcher.find_in_query(query)
            if not matched_keywords:
                return addresses

            # Collect all variations from matched keywords for text matching
            match_terms = set()
            for kw in matched_keywords:
                match_terms.add(kw.id.lower())
                for variation in getattr(kw, "match", []):
                    match_terms.add(variation.lower())

            boosted: list[Address] = []
            for addr in addresses:
                text = (addr.summary or "") + " " + (addr.location or "")
                text_lower = text.lower()
                boost = sum(1 for term in match_terms if term in text_lower)
                if boost > 0:
                    boosted.append(
                        Address(
                            kind=addr.kind,
                            source_id=addr.source_id,
                            location=addr.location,
                            summary=addr.summary,
                            score=addr.score + 0.1 * boost,
                            metadata=addr.metadata,
                        )
                    )
                else:
                    boosted.append(addr)
            return boosted
        except Exception as e:
            logger.warning(f"Keyword boost failed: {e}")
            return addresses

    def _deduplicate(self, addresses: list[Address]) -> list[Address]:
        """Deduplicate addresses by source_id+location, merging temporal tags."""
        seen: dict[tuple[str, str], int] = {}
        result: list[Address] = []

        for addr in addresses:
            key = (addr.source_id, addr.location)
            if key not in seen:
                seen[key] = len(result)
                result.append(addr)
            else:
                # Merge temporal_refs from duplicate into existing address
                new_refs = addr.metadata.get("temporal_refs", [])
                if new_refs:
                    idx = seen[key]
                    existing = result[idx]
                    existing_refs = existing.metadata.get("temporal_refs", [])
                    merged_refs = list(existing_refs)
                    for ref in new_refs:
                        if ref not in merged_refs:
                            merged_refs.append(ref)
                    if merged_refs != existing_refs:
                        meta = dict(existing.metadata)
                        meta["temporal_refs"] = merged_refs
                        result[idx] = Address(
                            kind=existing.kind,
                            source_id=existing.source_id,
                            location=existing.location,
                            summary=existing.summary,
                            score=max(existing.score, addr.score),
                            metadata=meta,
                        )

        return result

    @staticmethod
    def _enforce_file_diversity(addresses: list[Address], max_per_file: int = 3) -> list[Address]:
        """Reorder addresses so no single file monopolizes the top slots.

        Preserves ranking order but defers excess addresses from any one file
        to the end of the list. With max_per_file=3 and top_addresses=5,
        at least 2 different files appear in the top results.
        """
        file_counts: dict[str, int] = {}
        promoted: list[Address] = []
        deferred: list[Address] = []

        for addr in addresses:
            count = file_counts.get(addr.source_id, 0)
            if count < max_per_file:
                promoted.append(addr)
                file_counts[addr.source_id] = count + 1
            else:
                deferred.append(addr)

        return promoted + deferred
